* Coding
** String Inflections (word casing)

Easy transformation of word casing

#+begin_src emacs-lisp :tangle yes
    (use-package evil-string-inflection)
#+end_src

** Narrowing/Widen support

Add keybindings for narrowing in a function, and widen from narrows.

Narrowing allows me to do "update all" operations without affecting
the rest of the file, it also hides any other bit of code that might
be distracting.

#+begin_src emacs-lisp :tangle yes
  (use-package evil
    :config
    (evil-define-key 'normal prog-mode-hook (kbd "SPC c n f") #'narrow-to-defun)
    (evil-define-key 'normal prog-mode-hook (kbd "SPC c w") #'widen))
#+end_src

** Delimiter Setup (Parenthesis, Quotes, et al)

Following recommendations from [[https://www.reddit.com/r/emacs/comments/a6uepj/comment/ebysmzo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button][this Reddit thread]].

- Ensure there is autocompletion of quotes, parenthesis, etc.

  #+begin_src elisp :tangle yes
    (use-package smartparens
      :config
      (add-hook 'prog-mode-hook #'smartparens-mode))
  #+end_src

- Show matching parenthesis/quote/etc.

  This package is already included in emacs, so no need to
  call =use-package= on it.

  #+begin_src elisp :tangle yes
    (add-hook 'prog-mode-hook #'show-paren-mode)
  #+end_src

- [[https://github.com/emacsmirror/highlight-parentheses][highlight-parentheses]] to highlight the nested parens

  #+begin_src elisp :tangle yes
    (use-package highlight-parentheses
      :config
      (add-hook 'prog-mode-hook #'highlight-parentheses-mode))
  #+end_src

- Rainbow delimiters for deeply nested datastructures

  #+begin_src elisp :tangle yes
    (use-package rainbow-delimiters
      :config
      (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
  #+end_src

- [[https://github.com/emacs-evil/evil-surround][evil-surround]] for ease of editing content inside delimiters

  #+begin_src elisp :tangle yes
    (use-package evil-surround
      :config
      (global-evil-surround-mode 1))
  #+end_src

- [[https://github.com/redguardtoo/evil-matchit][evil-matchit]] to have a reliable match mechanism per language

  #+begin_src elisp :tangle yes
    (use-package evil-matchit
      :config
      (global-evil-matchit-mode 1))
  #+end_src

** LSP
*** Company mode

Use =company= to make lsp-mode happy

#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package company)
#+END_SRC

*** Core LSP

Add support for the Language Server Protocol APIs

#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package lsp-mode
    :after (evil)
    :hook ((lsp-mode . company-mode)
  	 ;; This is really annoying when lsp doesn't support a format command for a
  	 ;; specific mode, disabling for now.  (after-save . lsp-format-buffer)
  	 (lsp-mode . display-line-numbers-mode))

    :init
    (defun rapture/lsp-add-workspace (dir)
  	(interactive (list (read-directory-name "Directory: " default-directory)))
  	(lsp-workspace-folders-add dir))

    :config
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c p a") #'rapture/lsp-add-workspace)
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c d") #'lsp-find-definition)
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c D") #'lsp-find-references)
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c r") #'lsp-rename)
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c f") #'lsp-format-buffer)
    (setq lsp-enable-file-watchers nil)
    :custom
    (lsp-enable-snippet nil))
#+END_SRC

*** LSP UI

Add support for fancy lsp UI

#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package lsp-ui
    :after (lsp-mode)
    :hook (lsp-mode . lsp-ui-mode)
    :config
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c i") #'lsp-ui-imenu)
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c s") #'lsp-ui-doc-show)
    (evil-define-key 'normal lsp-mode-map (kbd "SPC c h") #'lsp-ui-doc-hide))
#+END_SRC

*** DAP mode (Debugging)

Allow me to run debuggers using the LSP framework

#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package dap-mode
    :init
    (setq dap-autoconfigure-features '(sessions locals controls tooltip))
    :after (lsp-mode)
    :hook (lsp-mode . dap-mode))
#+END_SRC
